services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/app
            - ./_docker/development/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "${APP_PORT}:80"
        depends_on:
            - php

    php:
        build:
            context: _docker/development
            dockerfile: php/Dockerfile
        volumes:
            - ./:/app
            - vendor:/app/vendor

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT}:80"
        depends_on:
            - db

volumes:
    postgres:
    pgadmin:
    vendor:
