services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./_docker/data/postgres:/var/lib/postgresql/data

  php:
    image: ravshan014/tour-crm-php:1
    restart: always
    environment:
      APP_ENV: prod
      APP_DEBUG: false
      APP_NAME: Tour CRM
      APP_URL: http://localhost
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  nginx:
    image: ravshan014/tour-crm-nginx:1
    ports:
      - "${APP_PORT}:80"
    restart: always
    depends_on:
      - php

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./_docker/data/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
