services:
  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - tour-crm-db:/var/lib/postgresql/data

  php:
    image: ravshan014/tour-crm-php:3
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_NAME: Tour CRM
      APP_URL: http://localhost
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
        db:
          condition: service_healthy

  nginx:
    image: ravshan014/tour-crm-nginx:1
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - php

  pgadmin:
    image: dpage/pgadmin4:8.14
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - tour-crm-pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  tour-crm-db:
  tour-crm-pgadmin:
