services:
  #  reverse-proxy:
  #    image: traefik:v3.1
  #    command:
  #      - "--providers.docker=true"
  #      - "--providers.docker"
  #      - "--providers.docker.exposedbydefault=false"
  #      - "--entryPoints.websecure.address=:443"
  #      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
  #      - "--certificatesresolvers.myresolver.acme.email=mro@mrodev.site"
  #      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  #      - "--entrypoints.web.address=:80"
  #      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  #      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  #    ports:
  #      - "80:80"
  #      - "443:443"
  #    volumes:
  #      - letsencrypt:/letsencrypt
  #      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./_docker/data/postgres:/var/lib/postgresql/data
  #      - tour-crm-db:/var/lib/postgresql/data

  php:
    build:
      context: .
      dockerfile: _docker/production/php/Dockerfile_2
    #    image: ravshan014/tour-crm-php:1
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: .
      dockerfile: _docker/production/nginx/Dockerfile
    #    image: ravshan014/tour-crm-nginx:1
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - php

  pgadmin:
    image: dpage/pgadmin4:8.14
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - tour-crm-pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy

volumes:
  tour-crm-db:
  tour-crm-pgadmin:
