services:
    nginx:
        image: nginx:1.22-alpine
        volumes:
            - ./:/app
            - ./_docker/development/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "${APP_PORT}:80"
        depends_on:
            - php

    php:
        build:
            context: _docker/development
            dockerfile: php/Dockerfile
        volumes:
            - ./:/app
            - vendor:/app/vendor

    db:
        image: postgres:17.2-alpine
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - ./_docker/development/postgres:/docker-entrypoint-initdb.d
            - ./_docker/data/postgres:/var/lib/postgresql/data
    #            - postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:8.14
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT}:80"
        depends_on:
            - db

#    mailhog:
#        image: mailhog/mailhog
#        restart: always
#        ports:
#            - "${MAILHOG_PORT}:8025"
#            - "1025:1025"
#        volumes:
#            - mailhog:/data

volumes:
    postgres:
    pgadmin:
    vendor:
    mailhog:
