services:
    nginx:
        build:
            context: .
            dockerfile: _docker/production/nginx/Dockerfile
        ports:
            - "${APP_PORT}:80"
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: _docker/production/php/Dockerfile
        volumes:
          - vendor:/app/vendor

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT}:80"
        depends_on:
            - db

volumes:
    postgres:
    pgadmin:
    vendor:
