<?php

namespace App\Filament\Resources\TransferBookingResource\RelationManagers;

use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;

class LegsRelationManager extends RelationManager
{
    protected static string $relationship = 'legs';

    // Legs are generated by TransferQuoteService::createBooking() and
    // shouldn't be hand-added/removed here — view only, edits happen on
    // the individual TransferRequest record if truly needed.
    public function form(Form $form): Form
    {
        return $form->schema([]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('from')
            ->columns([
                Tables\Columns\TextColumn::make('direction')
                    ->badge(),
                Tables\Columns\TextColumn::make('from'),
                Tables\Columns\TextColumn::make('to'),
                Tables\Columns\TextColumn::make('date_time')
                    ->dateTime(),
                Tables\Columns\TextColumn::make('passengers_count')
                    ->label(__('Passengers')),
                Tables\Columns\TextColumn::make('transportClass.name')
                    ->label(__('Vehicle')),
                Tables\Columns\TextColumn::make('vehicle_count')
                    ->label(__('Vehicles')),
                Tables\Columns\TextColumn::make('total_fare')
                    ->label(__('Fare'))
                    ->money('USD'),
                Tables\Columns\TextColumn::make('status')
                    ->badge(),
            ])
            ->headerActions([])
            ->actions([
                Tables\Actions\Action::make('edit')
                    ->label(__('Edit'))
                    ->icon('heroicon-o-pencil')
                    ->url(fn ($record) => \App\Filament\Resources\TransferRequestResource::getUrl('edit', ['record' => $record])),
            ])
            ->bulkActions([]);
    }
}
