name: CI Pipeline
on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Run tests
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

  #      - name: Cache Composer dependencies
  #        uses: actions/cache@v4
  #        with:
  #          path: vendor
  #          key: composer-${{ hashFiles('**/composer.lock') }}
  #          restore-keys: |
  #            composer-
  #
  #      - name: Install PHP
  #        uses: shivammathur/setup-php@v2
  #        with:
  #          php-version: 8.2
  #
  #      - name: Copy .env.testing
  #        run: |
  #          cp .env.testing .env
  #
  #      - name: Install Composer dependencies
  #        run: |
  #          composer install --no-interaction --no-progress --no-suggest
  #
  #      - name: Run tests
  #        run: |
  #          php artisan test
  #        env:
  #          DB_HOST: localhost
  #          DB_DATABASE: test
  #          DB_USERNAME: test
  #          DB_PASSWORD: 123456
  #
  #    services:
  #      postgres:
  #        image: postgres:17.2-alpine
  #        env:
  #          POSTGRES_DATABASE: test
  #          POSTGRES_USER: test
  #          POSTGRES_PASSWORD: 123456
  #        ports:
  #          - 5432:5432
  #        options: >-
  #          --health-cmd pg_isready
  #          --health-interval 10s
  #          --health-timeout 5s
  #          --health-retries 5

  deploy:
    name: Deploy
    needs: tests
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          cd ${{ secrets.APP_PATH }}
          ./build.sh

#  deploy:
#    name: Deploy
#    needs: tests
#    runs-on: self-hosted
#    steps:
#      - name: Deploy using ssh
#        uses: appleboy/ssh-action@v1.1.0
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            cd ${{ secrets.APP_PATH }}
#            ./build.sh
