name: CI Pipeline
on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Copy .env.testing
        run: |
          cp .env.testing .env

      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --no-progress --no-suggest

      - name: Run tests
        run: |
          php artisan test
        env:
          DB_HOST: localhost
          DB_DATABASE: test
          DB_USERNAME: test
          DB_PASSWORD: 123456

    services:
      postgres:
        image: postgres:17.2-alpine
        env:
          POSTGRES_DATABASE: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: 123456
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


